stages:
  - deploy

deploy:
  stage: deploy
  only:
    - master
  script:
    - apt-get update -y && apt-get install openssh-client -y && apt-get install -y rsync
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "Connecting to server"
    - ssh-keyscan -H "$SSH_HOST" >> ~/.ssh/known_hosts
    - ssh "$SSH_USER@$SSH_HOST"
    - echo "Connected to server"
    - cd $SSH_PATH
    - git pull origin master"
