stages:
  - deploy

before_script:
  - mkdir -p ~/.ssh
  - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - ssh-keyscan $SSH_HOST >> ~/.ssh/known_hosts

deploy:
  stage: deploy
  only:
    - master
  script:
    - ssh -vvv "$SSH_USER@$SSH_HOST"
    - echo "Connected to server"
    - cd $SSH_PATH
    - git pull origin master"
