stages:
  - deploy

deploy:
  stage: deploy
  script:
    - ssh "$SSH_USER@$SSH_HOST" -C "
      cd "$SSH_PATH";
      git pull origin master;
      sudo systemctl restart nginx;"
  only:
    - master
