stages:
  - deploy

deploy:
  stage: deploy
  only:
    - master
  script:
    - echo "Start deploying..."
    - 'which ssh-agent || (apt-get update -y && apt-get install openssh-client -y)'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    # Disable strict host key checking
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\tUserKnownHostsFile=/dev/null\n" > ~/.ssh/config
    - chmod 600 ~/.ssh/config
    - echo "Start pulling latest code..."
    - ssh -o StrictHostKeyChecking=no "$SSH_USER@$SSH_HOST" "cd $SSH_PATH && git pull origin master"
